\input texinfo   @@c -*-texinfo-*-
@c %**start of header
@setfilename sample.info
@settitle Sample Manual 1.0
@c %**end of header


@copying
This is a short example of a complete Texinfo file, version 1.0.

Copyright @copyright{} 2004 Free Software Foundation, Inc.
@end copying

@titlepage
@title Sample Title

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of contents at the beginning.
@contents

@ifnottex
@node Top
@top Short Sample

@insertcopying
@end ifnottex

@menu
* First Chapter::    The first chapter is the
                       only chapter in this sample.
* Second Chapter::
* Index::            Complete index.
@end menu


@node First Chapter
@chapter First Chapter

@cindex chapter, first

@cindex index entry, another

@enumerate
@item
This is the first item.

@item
This is the second item.
@end enumerate

@node Second Chapter
@chapter Second Chapter
@cindex chapter, second
     
@node Index
@unnumbered Index

@printindex cp

@bye
