/* Automatically generated by po2tbl.sed from apcupsd.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libintl.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"APCACCESS FATAL ERROR in %s at line %d\n", 2},
  {"Usage: %s (ipc) < reconfig | status | slave | shutdown >\n", 3},
  {"(ipc) <%s> : is not functional yet.\n", 4},
  {"%s (ipc) : polling apcupsd for %s.\n", 5},
  {"%s (ipc) <%s> : is not functional yet.\n", 6},
  {"Unknown command %s\n", 7},
  {"Cannot attach SYSV IPC.\n", 8},
  {"Cannot read shm data area.\n", 9},
  {"Strange mode\n", 10},
  {"UPS battery must be replaced", 11},
  {"Too Many Errors. Restarting UPS daemon", 12},
  {"Remote shutdown", 13},
  {"Power failure", 14},
  {"Running on UPS batteries", 15},
  {"Battery power exhausted", 16},
  {"Reached run time limit on batteries", 17},
  {"Battery charge below low limit", 18},
  {"Reached remaining time percentage limit on batteries", 19},
  {"Cancelling shutdown", 20},
  {"Power is back. UPS running on mains.", 21},
  {"Allowing logins", 22},
  {"Users requested to logoff", 23},
  {"User login prohibitted", 24},
  {"Battery power failure. Emergency shutdown", 25},
  {"error ignored.\n", 26},
  {"%s: Bogus configuration table! Fix and recompile.\n", 27},
  {"%s: Bogus configuration value (%s)\n", 28},
  {"%s: Exceeded max slaves number (%d)\n", 29},
  {"UPS function code %d missing\n", 30},
  {"Error opening configuration file (%s).\n", 31},
  {"\
%s: Warning: old configuration file found.\n\
\n\
%s: Expected: \"%s\"\n\
%s: Found:    \"%s\"\n\
\n\
%s: Please check new file format and\n\
%s: modify accordingly the first line\n\
%s: of config file.\n\
\n\
%s: Processing config file anyway.\n", 32},
  {"Parsing error at line %d of config file %s.\n", 33},
  {"%s: Error :: Changing UPSTYPE from %s ", 34},
  {"\
to %s due wrong Cable of Smart Signals.\n\
\\a", 35},
  {"Lookup operation failed: bad 'types' table\n", 36},
  {"I can't be both MASTER and SLAVE\n", 37},
  {"Terminating due to configuration file errors.\n", 38},
  {"start_thread: can not fork.", 39},
  {"%s: start_thread(%s).\n", 40},
  {"execute: cannot fork().", 41},
  {"execute: cannot exec %s", 42},
  {"read_lock: cannot increment read cnt.", 43},
  {"read_unlock: cannot unlock read sem.", 44},
  {"write_lock: cannot acquire write lock.", 45},
  {"write_lock: cannot assert write sem.", 46},
  {"write_unlock: cannot unlock write sem.", 47},
  {"create_semaphore: cannot create sem.\n", 48},
  {"create_semaphore: cannot set up sem.\n", 49},
  {"attach_semaphore: cannot attach sem.\n", 50},
  {"destory_semaphore: cannot destroy sem.\n", 51},
  {"create_shmarea: cannot create shm area.\n", 52},
  {"create_shmarea: cannot attach shm area.\n", 53},
  {"attach_shmarea: cannot get shm area.\n", 54},
  {"attach_shmarea: cannot attach shm area.\n", 55},
  {"attach_shmarea: shared memory version mismatch", 56},
  {"destroy_shmarea: cannot destroy shm area.\n", 57},
  {"\
usage: apcupsd [options]\n\
  Options are as follows:\n\
  -?, --help                display this help\n\
  -V, --version             display version info\n\
  -c, --configure           attempt to configure UPS [*]\n\
  -f, --config-file <file>  load specified config file\n\
  -u, --update-battery-date update UPS battery date [*]\n\
  -k, --killpower           attempt to power down UPS [*]\n\
  -d, --debug <level>       set debug level (>0)\n\
  -n, --rename-ups          attempt to rename UPS [*]\n\
\n\
  [*] Only one parameter of this kind and apcupsd must not run.\n\
\n\
Copyright (C) 1996-1999 Andre Hedrick\n\
Copyright (C) 1999-2000 Riccardo Facchetti\n\
apcupsd is free software and comes with ABSOLUTELY NO WARRANTY\n\
under the terms of the GNU General Public License\n\
\n\
Report bugs to apcupsd Support Center:\n\
  http://www.brisse.dk/site/apcupsd/\n", 58},
  {"\
\n\
Error: too many arguments.\n\
\n", 59},
  {"Status buffer overflow %d bytes\n", 60},
  {"Serial port already initialized.\n", 61},
  {"Cannot open UPS tty %s: %s\n", 62},
  {"Unable to create serial port lock file.\n", 63},
  {"PANIC! Cannot communicate with UPS.", 64},
  {"Shutdown not called first", 65},
  {"Bug found attempting to kill the power in %s at line %s", 66},
  {"Waiting 30 seconds for slave(s) to shutdown.", 67},
  {"Waiting 15 seconds for slave(s) to shutdown", 68},
  {"Attempting to kill the power!", 69},
  {"Failed to kill the power! Attempting a REBOOT!", 70},
  {"Perform CPU-reset or power-off", 71},
  {"Waiting For ShareUPS Master to shutdown", 72},
  {"Failed to have power killed by Master! Attempting a REBOOT!", 73},
  {"UPS will power off ...", 74},
  {"Mains-power returned during shutdown!", 75},
  {"Trying alternate method for killing power", 76},
  {"UPS power-cycle in progress ...", 77},
  {"Using non SU SmartUPS alternate method", 78},
  {"BackUPS Pro and SmartUPS v/s sleep for 6 min", 79},
  {"Unexpected error!", 80},
  {"Simple Cable Signal Lost!!!", 81},
  {"%s: INVALID-FORMATTING(%s) OLDDATE(%s)\n", 82},
  {"UPSlink Comm. Error, %s != SM count %d\n", 83},
  {"UPSlink Comm. reestablished, %s == SM count %d\n", 84},
  {"UPSlink Comm. Report, %s == SM count %d\n", 85},
  {"apcupsd exiting, signal %u\n", 86},
  {"shutdown succeeded", 87},
  {"error shutdown completed", 88},
  {"apcupsd FATAL ERROR in %s at line %d\n", 89},
  {"needs super user privileges to run.\n", 90},
  {"Cannot update battery date %s\n", 91},
  {"%s: attempting to update UPS battery date.\n", 92},
  {"done.\n", 93},
  {"This model cannot be configured.\n", 94},
  {"%s: attempting to configure UPS.\n", 95},
  {"Can not rename %s\n", 96},
  {"%s: attempting to rename UPS.\n", 97},
  {"**** FIXME ****", 98},
  {"\
NET Class Error %s\n\
\\a", 99},
  {"Unknown share net type\n", 100},
  {"%s: init_ipc failed.\n", 101},
  {"Can't fork.\n", 102},
  {"failed to reacquire serial port lock file on device %s\n", 103},
  {"Terminated.\n", 104},
};

int _msg_tbl_length = 104;
