#!/bin/sh
sftp -b - shell.sourceforge.net <<-END
	cd /home/groups/a/ap/apcupsd/htdocs
	-mkdir manual
	cd manual
	-rm *
	progress
	put apcupsd.pdf
	put apcupsd.html manual.html
	put apcupsd/*.html
	put apcupsd/*.css
	put apcupsd/*.png
END

