#!/bin/sh
cd /home/kern/apcupsd/k/doc/home-page
echo "Copying files to site"     
cp -f *.html /mnt/matou/home/www/apcupsd/public/docs/
cp -f *.gif /mnt/matou/home/www/apcupsd/public/docs/
cp -f mail16d.png /mnt/matou/home/www/apcupsd/public/docs/
